---
title: "Final Project"
author: "McCourt Hu, Lin Zuo, Jingyi Zhang, Yuanling Wang"
date: "12/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(mosaic)
library(forecast)
library(grid)
library(gridExtra)
library(rugarch)
library(scoringRules)
library(forcats)

set.seed(20181208)
df = read.csv("data.csv")
df$Open = as.numeric(as.character(df$Open))
df$High = as.numeric(as.character(df$High))
df$Low = as.numeric(as.character(df$Low))
df$Close = as.numeric(as.character(df$Close))
df$Adj.Close = as.numeric(as.character(df$Adj.Close))
df$Volume = as.numeric(as.character(df$Volume))
df$Date = as.Date(df$Date, format = "%d/%m/%Y")
df = df[complete.cases(df), ]
df = df %>% mutate(diff = Close - Open)

rmse = function(pred, truth){
  sqrt(mean((pred - truth)^2))
}

```

## EDA
```{r message=FALSE}
summary(df)

ggplot(data = df, aes(x = Stock, y = Close)) +
  geom_boxplot()

p1 = ggplot(data = df %>% filter(Stock == "Amazon") %>% arrange(Date), aes(x = Date, y = Close)) +
  geom_line() +
  ggtitle("Stock Close Price of Amazon")
p2 = ggplot(data = df %>% filter(Stock == "Apple") %>% arrange(Date), aes(x = Date, y = Close)) +
  geom_line() +
  ggtitle("Stock Close Price of Apple")
p3 = ggplot(data = df %>% filter(Stock == "Google") %>% arrange(Date), aes(x = Date, y = Close)) +
  geom_line() +
  ggtitle("Stock Close Price of Google")
p4 = ggplot(data = df %>% filter(Stock == "Facebook") %>% arrange(Date), aes(x = Date, y = Close)) +
  geom_line() +
  ggtitle("Stock Close Price of Facebook")
grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)

p1 = ggplot(data = df %>% filter(Stock == "Amazon") %>% arrange(Date), aes(x = Date, y = Open)) +
  geom_line() +
  ggtitle("Stock Open Price of Amazon")
p2 = ggplot(data = df %>% filter(Stock == "Apple") %>% arrange(Date), aes(x = Date, y = Open)) +
  geom_line() +
  ggtitle("Stock Open Price of Apple")
p3 = ggplot(data = df %>% filter(Stock == "Google") %>% arrange(Date), aes(x = Date, y = Open)) +
  geom_line() +
  ggtitle("Stock Open Price of Google")
p4 = ggplot(data = df %>% filter(Stock == "Facebook") %>% arrange(Date), aes(x = Date, y = Open)) +
  geom_line() +
  ggtitle("Stock Open Price of Facebook")
grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)

p1 = ggplot(data = df %>% filter(Stock == "Amazon") %>% arrange(Date), aes(x = Date, y = diff)) +
  geom_line() +
  ggtitle("Stock Price Daily Change of Amazon")
p2 = ggplot(data = df %>% filter(Stock == "Apple") %>% arrange(Date), aes(x = Date, y = diff)) +
  geom_line() +
  ggtitle("Stock Price Daily Change of Apple")
p3 = ggplot(data = df %>% filter(Stock == "Google") %>% arrange(Date), aes(x = Date, y = diff)) +
  geom_line() +
  ggtitle("Stock Price Daily Change of Google")
p4 = ggplot(data = df %>% filter(Stock == "Facebook") %>% arrange(Date), aes(x = Date, y = diff)) +
  geom_line() +
  ggtitle("Stock Price Daily Change of Facebook")
grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)

ggplot(data = cor(df %>% select(Close, Open, Volume, diff, High, Low)) %>% reshape2::melt(), aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() +
  ggtitle("Correltion matrix")

naive.lm = lm(data = df, formula = diff ~ as.factor(Stock) + Date)
naive.lm %>% summary()
ggplot() +
  geom_histogram(aes(x = naive.lm$residuals)) +
  xlab("Residuals") +
  xlim(c(-3, 3)) +
  ggtitle("Residual Plot")

df = df %>% mutate(naive.pred = naive.lm$fitted.values)
rmse(df$diff, df$naive.pred)
```

## Time Series Analysis and Models

$$
\begin{aligned}
Close_t &= Open_t + Diff_t\\
Diff_t &= ARIMA_{(p, q, d) \times (P, Q, D)_s}(Diff_{t-1, \cdots}) + \beta X
\end{aligned}
$$

```{r}
amazon.stock = df %>% filter(Stock == "Amazon") %>% arrange(Date)
ggtsdisplay(amazon.stock %>% select(diff), main = "Close Price")

ts.model = auto.arima(amazon.stock %>% select(diff), seasonal = TRUE)
ggtsdisplay(ts.model$residuals, main = "Arima(3, 0, 4)")
ts.model %>% summary()

amazon.stock = amazon.stock %>% mutate(ts.residuals = ts.model$residuals)

res.lm.model = lm(data = amazon.stock, formula = ts.residuals ~ 1)
res.lm.model %>% summary()

amazon.stock = amazon.stock %>% 
  mutate(ts.pred = ts.model$fitted + res.lm.model$fitted.values)
amazon.stock$residuals = c(amazon.stock$Close - amazon.stock$ts.pred)

ggplot(data = amazon.stock, aes(x = Date)) +
  geom_line(aes(y = Close, color = "red")) +
  geom_line(aes(y = Open + ts.pred, color = "blue")) +
  xlab("time") +
  ylab("Close Price of Amazon Stock") +
  ggtitle("ARIMA(3, 0, 4)")

rmse(amazon.stock$diff, amazon.stock$naive.pred)
rmse(amazon.stock$diff, amazon.stock$ts.pred)
forecast(ts.model, 30) %>% plot(xlim=c(5200, 5300))
```

```{r}
apple.stock = df %>% filter(Stock == "Apple") %>% arrange(Date)
ggtsdisplay(apple.stock %>% select(diff), main = "Close Price")

ts.model = auto.arima(apple.stock %>% select(diff), seasonal = TRUE)
ggtsdisplay(ts.model$residuals, main = "Arima(3, 0, 2)")
ts.model %>% summary()

apple.stock = apple.stock %>% mutate(ts.residuals = ts.model$residuals)

res.lm.model = lm(data = apple.stock, formula = ts.residuals ~ 1)
res.lm.model %>% summary()

apple.stock = apple.stock %>% 
  mutate(ts.pred = ts.model$fitted + res.lm.model$fitted.values)
apple.stock$residuals = c(apple.stock$diff - apple.stock$ts.pred)

ggplot(data = apple.stock, aes(x = Date)) +
  geom_line(aes(y = Close, color = "red")) +
  geom_line(aes(y = Open + ts.pred, color = "blue")) +
  xlab("time") +
  ylab("Close Price of Apple Stock") +
  ggtitle("ARIMA(3, 0, 2)")

rmse(apple.stock$diff, apple.stock$naive.pred)
rmse(apple.stock$diff, apple.stock$ts.pred)
forecast(ts.model, 30) %>% plot(xlim=c(9350, 9450))
```

```{r}
google.stock = df %>% filter(Stock == "Google") %>% arrange(Date)
ggtsdisplay(google.stock %>% select(diff), main = "Close Price")

ts.model = auto.arima(google.stock %>% select(diff), seasonal = TRUE)
ggtsdisplay(ts.model$residuals, main = "Arima(3, 0, 2)")
ts.model %>% summary()

google.stock = google.stock %>% mutate(ts.residuals = ts.model$residuals)

res.lm.model = lm(data = google.stock, formula = ts.residuals ~ 1)
res.lm.model %>% summary()

google.stock = google.stock %>% 
  mutate(ts.pred = ts.model$fitted + res.lm.model$fitted.values)
google.stock$residuals = c(google.stock$diff - google.stock$ts.pred)

ggplot(data = google.stock, aes(x = Date)) +
  geom_line(aes(y = Close, color = "red")) +
  geom_line(aes(y = Open + ts.pred, color = "blue")) +
  xlab("time") +
  ylab("Close Price of Google Stock") +
  ggtitle("ARIMA(3, 0, 2)")

rmse(google.stock$diff, google.stock$naive.pred)
rmse(google.stock$diff, google.stock$ts.pred)
forecast(ts.model, 30) %>% plot(xlim=c(3400, 3470))
```

```{r}
facebook.stock = df %>% filter(Stock == "Facebook") %>% arrange(Date)
ggtsdisplay(facebook.stock %>% select(diff), main = "Close Price")

ts.model = auto.arima(facebook.stock %>% select(diff), seasonal = TRUE)
ggtsdisplay(ts.model$residuals, main = "Arima(2, 0, 2)")
ts.model %>% summary()

facebook.stock = facebook.stock %>% mutate(ts.residuals = ts.model$residuals)

res.lm.model = lm(data = facebook.stock, formula = ts.residuals ~ 1)
res.lm.model %>% summary()

facebook.stock = facebook.stock %>% 
  mutate(ts.pred = ts.model$fitted + res.lm.model$fitted.values)
facebook.stock$residuals = c(facebook.stock$diff - facebook.stock$ts.pred)

ggplot(data = facebook.stock, aes(x = Date)) +
  geom_line(aes(y = Close, color = "red")) +
  geom_line(aes(y = Open + ts.pred, color = "blue")) +
  xlab("time") +
  ylab("Close Price of Apple Stock") +
  ggtitle("ARIMA(2, 0, 2)")

rmse(facebook.stock$diff, facebook.stock$naive.pred)
rmse(facebook.stock$diff, facebook.stock$ts.pred)
forecast(ts.model, 30) %>% plot(xlim=c(1450, 1520))
```

## Conclusion

## Discussion